version: "2"

services:
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
   # links: # Link selenium with webserver container.
     # - nginx

  behat:
    image: bergil/docker-behat
    environment:
      DOCKER_TESTING_ENVIRONMENT: 0 # 1 for testing sites on docker containers. Allowed: 0, 1.
    volumes:
      - {some path}/behat.yml:/srv/behat.yml # Mount behat.yml file as /srv/behat.yml.
      - {some path}/features:/srv/features # Mount features folder as /srv/features.
      - {some path}/artifacts:/srv/artifacts # Mount artifacts folder as /srv/artifacts.
      - {some path}/drupal8:/drupal  # Mount drupal root directory as /drupal (optional).
    links: # Link behat with selenium, webserver, database and web containers.
      - selenium
     # - nginx
     # - mariadb
     # - php
     depends_on: # Set after what services behat container shall start.
      - selenium
     # - nginx
     # - php
     # - mariadb
